### ISSUE TITLE
fails to install with pip2 

### ISSUE THREAD

**Issue by sosie-js** [SamuelJansen/globals#2]
Subtitution is not done on debian 10
when i trigger python2-7 setup.py install 
I get.

sh`Collecting globals

  Using cached globals-0.3.1.tar.gz (8.2 kB)

    ERROR: Command errored out with exit status 1:

     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-HhpmS_/globals/setup.py'"'"'; __file__='"'"'/tmp/pip-install-HhpmS_/globals/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Dvjln6
         cwd: /tmp/pip-install-HhpmS_/globals/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-HhpmS_/globals/setup.py", line 6
        url = **f'https://github.com/SamuelJansen/{name}/'**
                                                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`sh

**Comment by SamuelJansen** [comment]
Globals works only on python 3.6+ and further

setup says 3.9 and further, but I tested in several versions of python 3.6+ and it compiles just fine.
https://github.com/SamuelJansen/globals/blob/master/setup.py

![image](https://user-images.githubusercontent.com/46162680/119742810-f1ed5c00-be5e-11eb-9ae6-7038bd05bf21.png)

==========================================
Now about your case, which is on debian.

You can download, compile and install python3 yourself. 
There are several ways to do so.

Here is a great tutorial for python 3.9.1
https://linuxize.com/post/how-to-install-python-3-9-on-debian-10/#disqus_thread
I don't know about the author, but its a great tutorial.

==========================================
Fell free to reach out
Have fun coding

**Comment by sosie-js** [comment]
Ok, thanks for this Samuel.
